### PR TITLE
Add note that template is auto-generated

### PR DESCRIPTION
**Pull request by Xe**
```go
// Generated by ego on Fri Mar 13 00:50:33 2015
// DO NOT EDIT
```

### CODE REVIEW

**Comment by benbjohnson** [comment]
:+1:

**Comment by scorredoira** [comment]
Hi, the problem with including the generation date is that your version control system 
will detect changes event if you didn't change the source.

**Comment by Xe** [comment]
Don't run the template generator if you haven't changed anything?

**Comment by scorredoira** [comment]
If you call the command manually of course it makes no sense to call it when you have no changrs, but if you have a bunch of go generate lines with different actions including ego then is when it becomes anoying.

**Comment by scorredoira** [comment]
We could add a flag to avoid including the timestamp. Anyway is no big deal.

**Comment by benbjohnson** [comment]
@scorredoira I removed the timestamp from the header in https://github.com/benbjohnson/ego/pull/16. Sorry for taking so long! :)

**Comment by scorredoira** [comment]
No problem, thanks!

**Pull request merged**
